# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pokkum < Formula
  desc "Zero-dependency OCI container image compiler for SvelteKit applications"
  homepage "https://github.com/CreativeBeastDesign/pokkum"
  version "1.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/CreativeBeastDesign/Pokkum/releases/download/v1.0.1/pokkum_1.0.1_darwin_amd64.tar.gz"
      sha256 "bd1a3a21f0c58b78cddaf1f1d1049f8b785d18c54d550b53208b70212d50af82"

      define_method(:install) do
        bin.install "pokkum"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/CreativeBeastDesign/Pokkum/releases/download/v1.0.1/pokkum_1.0.1_darwin_arm64.tar.gz"
      sha256 "dafe914d2f9ef747b85f8fa54c772bccc299b076fe6ed1a240262df207eb7be7"

      define_method(:install) do
        bin.install "pokkum"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/CreativeBeastDesign/Pokkum/releases/download/v1.0.1/pokkum_1.0.1_linux_amd64.tar.gz"
      sha256 "7556f9e90f28861399568f22061b122e57b509020f372f4031e24727a05e3b40"
      define_method(:install) do
        bin.install "pokkum"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/CreativeBeastDesign/Pokkum/releases/download/v1.0.1/pokkum_1.0.1_linux_arm64.tar.gz"
      sha256 "ee9001ff52bf1d856a4ac35c1d855c42e02f3486551562a99d7fc1ab82652a98"
      define_method(:install) do
        bin.install "pokkum"
      end
    end
  end
end
