# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pokkum < Formula
  desc "Zero-dependency OCI container image compiler for SvelteKit applications"
  homepage "https://github.com/CreativeBeastDesign/pokkum"
  version "1.0.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/CreativeBeastDesign/Pokkum/releases/download/v1.0.6/pokkum_1.0.6_darwin_amd64.tar.gz"
      sha256 "1b375186490eeffc5373e281f09db9bbeaa16d952900b63e303b555124edfae8"

      define_method(:install) do
        bin.install "pokkum"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/CreativeBeastDesign/Pokkum/releases/download/v1.0.6/pokkum_1.0.6_darwin_arm64.tar.gz"
      sha256 "bf5478abae240f16298ec63f701e1396f4e819c36c00bdf82e82cbefa7397dac"

      define_method(:install) do
        bin.install "pokkum"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/CreativeBeastDesign/Pokkum/releases/download/v1.0.6/pokkum_1.0.6_linux_amd64.tar.gz"
      sha256 "f1fbad8ef9caa9a80ab0b90578545bfb681a5d67e0da3ea5a0369e1c20ac3a7a"
      define_method(:install) do
        bin.install "pokkum"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/CreativeBeastDesign/Pokkum/releases/download/v1.0.6/pokkum_1.0.6_linux_arm64.tar.gz"
      sha256 "bd28b262dfb771ccdc9ad702a1ecc16163332dd51cfd2595222f2294ca0f3d93"
      define_method(:install) do
        bin.install "pokkum"
      end
    end
  end
end
